from re import S
from tkinter import ttk

class CreateExcelFrame(ttk.Frame):
    def __init__(self,container):
        super().__init__(container)
        # main frame: two rows (selector and buttons)
        self.rowconfigure(0, weight = 4)
        self.rowconfigure(1, weight = 1)
        self.columnconfigure(0, weight = 2)
        self.columnconfigure(1, weight = 3)
        # selector frame
        sheetChooseFrame = ttk.Frame(self)
        sheetChooseFrame.columnconfigure(0, weight= 1)
        sheetChooseFrame.grid(row=0, column=0, padx=(100,0), sticky="NSEW")
        terminalFrame = ttk.Frame(self, style='customFrame.TFrame')
        terminalFrame.columnconfigure(0, weight=1)
        terminalFrame.grid(row=0, column=1, pady=(150), padx=(0,100))
        selectorTitle = ttk.Label(sheetChooseFrame,text="Create sheet for", style='selectorTitle.TLabel')
        selectorTitle.grid(pady=50, sticky="NW")
        multipleChoiceCheckbox = ttk.Checkbutton(sheetChooseFrame,text="Multiple choice")
        multipleChoiceCheckbox.grid(sticky='NW')
        oneAnswerCheckbox = ttk.Checkbutton(sheetChooseFrame,text="One answer")
        oneAnswerCheckbox.grid(sticky='NW')
        numericCheckbox = ttk.Checkbutton(sheetChooseFrame,text="Numeric")
        numericCheckbox.grid(sticky='NW')
        trueFalseCheckbox = ttk.Checkbutton(sheetChooseFrame,text="True / false")
        trueFalseCheckbox.grid(sticky='NW')
        createDemoDataCheckbox = ttk.Checkbutton(sheetChooseFrame, text="Create demo data")
        createDemoDataCheckbox.grid(sticky='NW', pady=50)
        # terminalTitle = ttk.Label(terminalFrame,text="Output", style='terminalFontTitle.TLabel')
        # terminalTitle.grid(pady=(0,50), sticky="N")
        multipleChoiceTerminalLabel = ttk.Label(terminalFrame,text="Multiple choice questions generated: ", style='terminalFont.TLabel')
        multipleChoiceTerminalLabel.grid(sticky='NW')
        oneAnswerTerminalLabel = ttk.Label(terminalFrame,text="One answer questions generated: ", style='terminalFont.TLabel')
        oneAnswerTerminalLabel.grid(sticky='NW')
        numericTerminalLabel = ttk.Label(terminalFrame,text="Numeric questions generated: ", style='terminalFont.TLabel')
        numericTerminalLabel.grid(sticky='NW')
        trueFalseTerminalLabel = ttk.Label(terminalFrame,text="True / false questions generated: ", style='terminalFont.TLabel')
        trueFalseTerminalLabel.grid(sticky='NW')

        # buttons frame
        buttonsFrame = ttk.Frame(self)
        buttonsFrame.columnconfigure(0, weight = 1)
        buttonsFrame.columnconfigure(1, weight = 1)
        buttonsFrame.columnconfigure(2, weight = 1)
        buttonsFrame.grid(row=1, column=0, columnspan=2)
        button = ttk.Button(buttonsFrame, text = "Create file", style = "Custom.TButton")
        button2 = ttk.Button(buttonsFrame, text = "Open file", style = "Custom.TButton")
        button3 = ttk.Button(buttonsFrame, text = "Open folder", style = "Custom.TButton")
        button.grid(row=0,column=0, sticky="NS", padx=25, pady=5)
        button2.grid(row=0,column=1, sticky="NS", padx=25, pady=5)
        button2.state(['disabled'])
        button3.grid(row=0,column=2, sticky="NS", padx=25, pady=5)
        button3.state(['disabled'])